### PR TITLE
ev3: fix display fb handling for new kernel

### LINKED ISSUE #2: display driver changes in ev3dev-2.0.0 kernel
In ev3dev-stretch, we are now using the mainline kernel driver for the display on the EV3. Unfortunately, this driver does not have support for monochrome. The video memory now uses a 32 bit per pixel layout (XRGB) instead of the one bit per pixel packed format. The plus side is that the screen is actually two bit per pixel grayscale, so we can actually use that feature now, but it means the current hard-coded LCD code is now broken.

### PR DESCRIPTION
**Pull request by kortschak**
@dlech Please take a look.

This was even easier than I had guessed.

Fixes #2.

### CODE REVIEW

**Comment by dlech** [comment]
Your image is RGBA, but the framebuffer is XRGB, so if you are writing the image directly to the framebuffer, it won't work exactly right.

**Comment by kortschak** [comment]
I was operating on the basis that the fb packing is big endian, which I got from the fbset source (in the absence of any real documentation to that effect - so certainly possible wrong). This means that the A will get put in the last slot and be ignored. If it is actually little endian, then I'll either have to wrap `image.RGBA` or probably more likely just reimplement the type with the order reversed and dropping A.

**Comment by dlech** [comment]
You could very well be right, but then wouldn't R and B would be swapped.

If you go to the route of re-implementing, you might consider using an 8-bit grayscale image (the EV3 screen is actually only 2-bit grayscale, but 8-bit is the closest "standard" format). Then when you push the image to the screen, use the same 8-bit pixel value for each of RGB.

**Comment by kortschak** [comment]
I'll do the experiments to see if what is going on. As far as making the image type handle an 8 bit greyscale, that's handled by the stdlib image/color code; an image copy of a greyscale to the fb will just work. Do we have a gamut mapping of colour values to the grey scale bits, or it just linear?

**Comment by dlech** [comment]
The kernel driver does the mapping from RGB to grayscale.

```C
/**
 * tinydrm_xrgb8888_to_gray8 - Convert XRGB8888 to grayscale
 * @dst: 8-bit grayscale destination buffer
 * @vaddr: XRGB8888 source buffer
 * @fb: DRM framebuffer
 * @clip: Clip rectangle area to copy
 *
 * Drm doesn't have native monochrome or grayscale support.
 * Such drivers can announce the commonly supported XR24 format to userspace
 * and use this function to convert to the native format.
 *
 * Monochrome drivers will use the most significant bit,
 * where 1 means foreground color and 0 background color.
 *
 * ITU BT.601 is used for the RGB -> luma (brightness) conversion.
 */
```

**Comment by kortschak** [comment]
The [code for that](https://github.com/torvalds/linux/blob/26ed24e429d89e045e5eb2d2b75215244347b7f2/drivers/gpu/drm/tinydrm/core/tinydrm-helpers.c#L185-L237) is very helpful.

It looks like the endianism is machine-endian and (as the name suggests) `00rrggbb`. The conversion is straightforward, but we still need to take a `color.Color`; the good thing is that the grey colours provided in `color` already implement the ITU BT.601.

In the [kernel](https://github.com/torvalds/linux/blob/26ed24e429d89e045e5eb2d2b75215244347b7f2/drivers/gpu/drm/tinydrm/core/tinydrm-helpers.c#L229):
```
			/* ITU BT.601: Y = 0.299 R + 0.587 G + 0.114 B */
```
In [`color`](https://github.com/golang/go/blob/c5f0104daf974ad8ef736dfa7cb44059ac293291/src/image/color/color.go#L244-L277):
```
func grayModel(c Color) Color {
	if _, ok := c.(Gray); ok {
		return c
	}
	r, g, b, _ := c.RGBA()


	// These coefficients (the fractions 0.299, 0.587 and 0.114) are the same
	// as those given by the JFIF specification and used by func RGBToYCbCr in
	// ycbcr.go.
	//
	// Note that 19595 + 38470 + 7471 equals 65536.
	//
	// The 24 is 16 + 8. The 16 is the same as used in RGBToYCbCr. The 8 is
	// because the return value is 8 bit color, not 16 bit color.
	y := (19595*r + 38470*g + 7471*b + 1<<15) >> 24


	return Gray{uint8(y)}
}


func gray16Model(c Color) Color {
	if _, ok := c.(Gray16); ok {
		return c
	}
	r, g, b, _ := c.RGBA()


	// These coefficients (the fractions 0.299, 0.587 and 0.114) are the same
	// as those given by the JFIF specification and used by func RGBToYCbCr in
	// ycbcr.go.
	//
	// Note that 19595 + 38470 + 7471 equals 65536.
	y := (19595*r + 38470*g + 7471*b + 1<<15) >> 16


	return Gray16{uint16(y)}
}
```

This means that all that's needed is the correct byte order to be written to the byte buffer that reflects the fb.

**Comment by kortschak** [comment]
This will fail since it will try to build against master. I'll ping after having done successful tests on actual hardware over the weekend.

**Comment by kortschak** [comment]
Tested and working (failure here is due to the dependency on the ev3dev-stretch branch).

**Comment by kortschak** [comment]
PTAL

**Review by dlech — APPROVED** [review]
not much to see :smile:

**Comment by kortschak** [comment]
Indeed!

**Pull request merged**
